### ISSUE TITLE
Comments & questions on Anoma's execution model

### ISSUE THREAD

**Issue by sergio-mena** [informalsystems/partnership-heliax#1]
In the last couple of days, we have looked into the specification of Anoma's execution model. We understand we need to be familiar with it in order to do a thorough review of Anoma's PoS (as well as other parts of the system in the future).

This is a list of questions we came up with while going through the execution model's spec:

* Accounts
  * The definition of _account_ (and what it represents) is somewhat special in Anoma, and plays a key role in understanding the rest. We believe a broad description of accounts and how they are used (possibly with examples) should be easily found in the spec. So far, we found [this](/anoma/anoma/blob/c366704/docs/src/explore/design/ledger/accounts.md).
  * Further on this topic, the spec talks about "Special Anoma accounts". What are those? How are they different from "normal" accounts? Is it just those accounts that have (1) an internal address, and (2) a native validity predicate? Or is there more to it?

* Changes to validity predicates
  * Is there a difference between native VPs and WASM-based ones regarding the rules for changing them?
  * Regarding the text specifying VP changes, we could find a paragraph at the end of the [Validity predicates page](/anoma/anoma/blob/c366704/docs/src/explore/design/ledger/vp.md) which applied to particular VP, but we found nothing general concerning the rules of changing VPs. Is there documentation/specification work on this?

* Regarding the VP's _host functions_, what is the difference between `read_bytes_pre` and `read_bytes_temp` ?
  * Looking into the code, we got to [this](/anoma/anoma/blob/c366704/vm_env/src/imports.rs#L578), [this](/anoma/anoma/blob/c366704/vm_env/src/imports.rs#L585), and [this](/anoma/anoma/blob/c366704/vm_env/src/imports.rs#L592); whose docstrings use terms _prior_, _posterior_, and _temporary_. Are these defined somewhere in the spec?

* Regarding ABCI, the spec says [here](/anoma/spec/blob/1e357d6/src/architecture/m1/execution-system.md#anoma-ledger) that Anoma defers transaction execution from `DeliverTx` to `Endblock`. The reasons given are DKG and ABCI++.
  * The problem we see with this approach is that it will not be possible to provide the results of the transaction (called `tx_results` in ABCI++) while in ABCI. Tendermint hashes these into the next block's header, so it is a valuable asset when troubleshooting non-determinism issues.
  * Also, bear in mind that `DeliverTx` and `Endblock` (together with `BeginBlock`) will be collapsed into `FinalizeBlock` in ABCI++, which might defeat the purpose of this deviation.

**Comment by sergio-mena** [comment]
Coming back to this issue after a while (trying to drive old issues to completion).
I looked at the specs as they are now, and I can no longer find these validity predicates: [parameter_vp](https://github.com/anoma/spec/blob/1e357d6/src/architecture/m1/governance.md?plain=1#L278) and [governance_fund_pool_vp](https://github.com/anoma/spec/blob/1e357d6/src/architecture/m1/governance.md?plain=1#L236).

Do they still exist? Have they been moved/renamed?

**Comment by tzemanovic** [comment]
@sergio-mena the page has been moved to https://github.com/anoma/namada/blob/main/documentation/specs/src/base-ledger/governance.md

**Comment by sergio-mena** [comment]
Thanks @tzemanovic, I went to the new spec, which points to the current implementations of these two VPs, [here](https://github.com/anoma/namada/blob/master/shared/src/ledger/governance/mod.rs#L46) and [here](https://github.com/anoma/namada/blob/main/shared/src/ledger/treasury/mod.rs#L55).

As they turn the set of keys into an iterator and then use the iterator's method "all", the flaw idetified in [this comment](https://github.com/informalsystems/partnership-heliax/issues/1#issuecomment-1080898788) above no longer applies as "all" will process all keys until it finds the closure returning "false" on an element. Thus the order of the keys becomes irrelevant (remember that the predicates [here](https://github.com/anoma/spec/blob/1e357d6/src/architecture/m1/governance.md?plain=1#L278) and [here](https://github.com/anoma/spec/blob/1e357d6/src/architecture/m1/governance.md?plain=1#L236) always returned in the first iteration of the loop).
