### ISSUE TITLE
Interplay between bonding and deactivate

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#10]
When we run tx_deactivate, we don't look up all the possible bond operations that are still ongoing (i.e., no unbond done yet). So, all those bonds are somehow dangling. The model works because, tx_undelegate and tx_unbond don't check the status, so the delegator can use them to get the tokens back.

However, what does it mean to have an "ongoing" bonding on a validator that was deactivated? And, when the delegator finally executes tx_undelegate, shall it still wait for the unbonding period?

**Comment by angbrav** [comment]
My guess is that this is not an issue:

It should be up to the users to realize that a validator is not active anymore and claim their tokens back. Regarding whether to still wait for the unbonding period or not, I guess that the rule should be to wait at least unbonding_length from the epoch the validator became inactive. So there should be ways to optimize the model, but it is "safe" in its current shape.

**Comment by sergio-mena** [comment]
Your answer makes sense to me. Also, if a validator reactivates, I guess those "dangling" bonds are not active again, as though the delegations had taken place at the time of reactivate. Is this a good way to "understand" this case?

**Comment by angbrav** [comment]
The approach is that it is the user's responsibility to keep track of the validators' status and act upon it. For instance, if a user bonds tokens to an inactive validator, it won't get rewards and it is up to the user to realize this and unbond. 

We've agreed to close the issue.
