### ISSUE TITLE
PoS invariants

### ISSUE THREAD

**Issue by tzemanovic** [informalsystems/partnership-heliax#25]
Brain storming some more invariants to check in PoS model:

- Disregarding any slashes or staking rewards (we're not modeling rewards yet), an amount that is self-bonded or delegated is exactly equal to the amount that can be withdrawn back from PoS (in other words, if all the bonds are withdrawn, the PoS balance must be equal to zero)
- For a validator who gets slashed for some rate of tokens, the total slashed token amount must be equal to the sum of slashed amounts on each bond to this validator that is liable for the slash (self-bonds and delegations).
- A bond submitted at epoch `n` cannot affect voting power of a target validator before epoch `n + pipeline_len`  
- bonding and unbonding applied in the same epoch preserve composition. I.e. a bond of amount `z` submitted in an epoch `e` has the same effect as 2 bonds applied in epoch `e` of amounts `x` and `y`, where `x + y = z`
- I don't think we actually have the active/inactive validator sets in the model, so not sure if these invariant are useful or even something that we'd want to check, but here goes:
	- The length of active validator set is always <= `max_validator_slots` parameter
	- A validator account is always in either in active or inactive validator set, unless it is jailed, in which case it is in neither
	- The lowest active validator's voting power is >= greatest inactive validator's voting power
	- The validators sets use a stable sort - The order of validators in the validator sets positions is preserved when there are multiple validators with the same voting power

**Comment by angbrav** [comment]
Agreed to look into the first two bullets. The third and the fourth trivially hold by construction. The fifth would require a new TLA+ model (or extending the current one).
