### ISSUE TITLE
Interplay between slashing, bonds and repeated infractions

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#27]
I am not sure if the following is intended, but it looks wrong to me.

Assume that a validator misbehaves twice (this could be generalized to an unbounded number of infractions), but with enough epochs between infractions for the PoS system to punish it (a window of unbonding_length to be specific). Assume the validator starts with X bonded tokens and no user bonds or unbonds before the second infraction. Assume that the final slash rate is 0.2 for both infractions. The first slash rate is applied to X and the second to X*0.8. Therefore, the total slashed amount is `X*0.2 + X*0.8*0.2 = X*0.36`.

For simplicity, assume that all X tokens were bonded by a single user in a single action. Assume that the user after the second infraction is processed unbonds X tokens and eventually calls withdraw. Both infractions are going to be applied to the amount X, leading to a higher slashed amount: `X*0.2 + X*0.2 = X*0.4`.

In case something is unclear, here is a spelled-out execution (with epochs and variables):

- Let `validators[val].total_deltas[e] = x` and assume that belongs to a single `bond` issued by `user`.
- Assume now that some evidence is found at `e` for an action `val` did at epoch e. Then `val` gets frozen at `e` and the evidence is processed at the end of epoch `e+unbonding_length`.
- Assume that the rate for the evidence in `0.2`. Then, after processing the evidence, `validators[val].total_deltas[e+unbonding_length+1] = 0.8*x` and `val` is not frozen anymore.
- Assume that the validator misbehaves again at `e+unbonding_length+1`. The evidence will be processed by the end of `e+2*unbonding_length+1`.
- Assume that the rate for the evidence in `0.2`. Then, after processing the evidence, `validators[val].total_deltas[e+2*unbonding_length+2] = 0.8*x - 0.16*x = 0.64*x`  and `val` is not frozen anymore. This means that `0.36*x` has been slashed. 
- Assume that `user` unbonds `a1` by `e+2*unbonding_length+2`. Then the unbond will be withdrawable by `e+pipeline_lenght+3*unbonding_length+2`.
- Assume that user withdraws at `e+pipeline_lenght+3*unbonding_length+2`. There will be two slashes to apply. One would expect that the total slashed amount is `0.36*x`. Nevertheless, we apply the slash rates to the bonded amount and this does not get updated when infractions are processed.
- In more detail. The slashed amount will be `0.2*x + 0.2*x = 0.4*x > 0.36*x`

I do not see a simple solution for this, so let's first discuss whether this is intended or not. This disregards jailing, but the way it is modeled, the validator could be unjailed after a minimum sentence, so the concern remains.

**Comment by sergio-mena** [comment]
Minor.
> Assume that the validator misbehaves again at e+unbonding_length+1. The evidence will be processed by the end of `e+2*unbonding_length+1`

Won't it be processed at the end of `e+2*unbonding_length+2` ?

Also, when the text says `e+2*unbonding_length+2`, I would say it is `e+2*unbonding_length+3`

**Comment by sergio-mena** [comment]
Indeed I see the discrepancy you refer to.
My first reaction would be: since we have a full TLA+ model, is it possible to come up with an invariant that would summarize the concern described by the example, and then check it against the model to get invalid traces?
That would later help make sure that, when we agree on a solution and change the model accordingly, we can double-check that the invariant is no longer violated.

**Comment by angbrav** [comment]
> Minor.
> 
> > Assume that the validator misbehaves again at e+unbonding_length+1. The evidence will be processed by the end of `e+2*unbonding_length+1`
> 
> Won't it be processed at the end of `e+2*unbonding_length+2` ?
> 

I do not think so. When evidence is found, we schedule it to be processed at the misbehaving epoch + unbonding _length. Therefore, if we find out that a validator misbehaved at `e+unbonding_length+1`, then the evidence will be processed at the end of `e+unbonding_length+1 + unbonding_length = e+2*unbonding_length+1`.

**Comment by angbrav** [comment]
> Indeed I see the discrepancy you refer to. My first reaction would be: since we have a full TLA+ model, is it possible to come up with an invariant that would summarize the concern described by the example, and then check it against the model to get invalid traces? That would later help make sure that, when we agree on a solution and change the model accordingly, we can double-check that the invariant is no longer violated.

I think we already have one that checks this: I believe user accounts will go negative in some executions.

**Comment by angbrav** [comment]
Model-checker does not complain in execution with repeated slashes, so I am closing this as resolved

**Comment by angbrav** [comment]
The model-checker does not complain in executions with repeated infractions, so I am closing this.
