### ISSUE TITLE
Validator's slashing is wrong due to ongoing unbonds and bonds

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#34]
I think I have found an issue with the way we are computing slashing for validators at the end of an epoch. I think the issue is related to the fact that bonds can be unbonded before these are reflected in `totalDeltas`. See the following:

Assume that `pipeline_length=1`and `unbonding_lenght=2`. Assume that `slash_rate=1` for simplicity and a single `user` and a validator `val`.
Assume the following execution:
- `epoch=0`:
  - `user` delegates `10` tokens to `val`.
  - `val.totalDeltas[0]= 0, val.totalDeltas[>=1]=10`
  - `bonds[user][val] = {[amount |-> 10, start |-> 1]}
- `epoch=3`
  -  `user` delegates `12` tokens to `val`.
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[>=4]=22`
  - `bonds[user][val] = {[amount |-> 10, start |-> 1], [amount |-> 12, start |-> 4]}
- `epoch=4`
  -  `user` unbonds `22` tokens from `val`.
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[4]=22`, val.totalDeltas[>=5]=0`
  - `bonds[user][val] = {}`
  - `unbonds[user][val] = {[amount |-> 10, start |-> 1, end |-> 7], [amount |-> 12, start |-> 4,  end |-> 7]}`
  - `val.totalUnbonded[0,1,2,3,4]=0, val.totalUnbonded[5]=22`
  - evidence submitted for `val` at `epoch=3`. Will be processed at the end of epoch 5.
- `epoch=5`
  -  process evidence in `end_of_epoch()` function
  - `total_staked=val.totalDeltas[3]=10`
  - `total_unbonded=val.totalUnbonded[4]+val.totalUnbonded[5]=22`
  - for `offset=1` -> `total_unbonded=total_unbonded+val.totalUnbonded[6]=22`
                                  `this_slash=total_staked-total_unbonded=10-22=-12`
                                  `diff_slashed_amount=last_slash - this_slash=0 - (-12)= 12`
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[4,5]=22, val.totalDeltas[>=6]=12`
                              
 We have to figure how to compute slashes correctly.

**Comment by angbrav** [comment]
I think the solution is simple: we need to keep a second variable `totalBonded` and add it when computing the slash amount. I haven't thought very carefully about it but it solves this execution at least. I'd say it is a good lead!
Here's the execution again but introducing this new variable. Note that we do not need to keep both, we could simply keep one that we increase with bonds and decrease with unbonds.

Assume that `pipeline_length=1`and `unbonding_lenght=2`. Assume that `slash_rate=1` for simplicity and a single `user` and a validator `val`.
Assume the following execution:
- `epoch=0`:
  - `user` delegates `10` tokens to `val`.
  - `val.totalDeltas[0]= 0, val.totalDeltas[>=1]=10`
  - `bonds[user][val] = {[amount |-> 10, start |-> 1]}
  - `totalBonded[0]=0, totalBonded[1]=10`
- `epoch=3`
  -  `user` delegates `12` tokens to `val`.
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[>=4]=22`
  - `bonds[user][val] = {[amount |-> 10, start |-> 1], [amount |-> 12, start |-> 4]}
  - `totalBonded[0]=0, totalBonded[1]=10, totalBonded[2,3]=0, totalBonded[4]=12`
- `epoch=4`
  -  `user` unbonds `22` tokens from `val`.
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[4]=22`, val.totalDeltas[>=5]=0`
  - `bonds[user][val] = {}`
  - `unbonds[user][val] = {[amount |-> 10, start |-> 1, end |-> 7], [amount |-> 12, start |-> 4,  end |-> 7]}`
  - `val.totalUnbonded[0,1,2,3,4]=0, val.totalUnbonded[5]=22`
  - evidence submitted for `val` at `epoch=3`. Will be processed at the end of epoch 5.
- `epoch=5`
  -  process evidence in `end_of_epoch()` function
  - `total_staked=val.totalDeltas[3]=10`
  - `total_unbonded=val.totalUnbonded[4]+val.totalUnbonded[5]=22`
  - `total_bonded=val.totalBonded[4]+val.totalBonded[5]=12`
  - for `offset=1` -> `total_unbonded=total_unbonded+val.totalUnbonded[6]=22`
                                  `total_bonded=total_bonded+val.totalBonded[6]=12`
                                  `this_slash=total_staked-total_unbonded+total_bonded=10-22+12=0`
                                  `diff_slashed_amount=last_slash - this_slash=0 - 0= 0`
  - `val.totalDeltas[0]=0, val.totalDeltas[1,2,3]=10, val.totalDeltas[4,5]=22, val.totalDeltas[>=6]=12`

**Comment by angbrav** [comment]
The more I think about this, the more convinced I am that we need to know if the unbonded tokens were contributing to the validator's stake when this misbehaved. This can be done trivially by iterating over the unbonds but I know this is expensive and we try to avoid it. I am thinking of the alternative of keeping in `total_unbonded` instead the sum of all unbonded tokens at a given epoch, a set of records to record when the bond started. I think this is a reasonable alternative.

Let me know what you think. Meanwhile, I'll try to spell out the idea and come up with an execution that motivates the above.

**Comment by tzemanovic** [comment]
> The more I think about this, the more convinced I am that we need to know if the unbonded tokens were contributing to the validator's stake when this misbehaved. This can be done trivially by iterating over the unbonds but I know this is expensive and we try to avoid it. I am thinking of the alternative of keeping in `total_unbonded` instead the sum of all unbonded tokens at a given epoch, a set of records to record when the bond started. I think this is a reasonable alternative.
> 
> Let me know what you think. Meanwhile, I'll try to spell out the idea and come up with an execution that motivates the above.

I see - adding a bond start to `total_unbonded` sounds like a good idea. We'll be able to add up the unbond amounts with a same start epoch, so it's a lot better than using the unbonds themselves.

**Comment by angbrav** [comment]
Closed by #37

**Comment by angbrav** [comment]
I think we've forgotten something. We are taking from something we have already slashed (`totalDeltas`) something that has not been slashed (`unbonds`). This is wrong. When folding over `total_unbonds` to computed `total_unbonded`, we should consider already processed slashes. It is kind of easy to see why this is wrong:
- Assume a user delegates 100 tokens to a validator at epoch 1
- Assume that the validator misbehaves at epoch 2 and it is slashed 50%
- Assume that at a epoch 20, the user unbonds the 100 tokens. 
- Now the validator misbehaves again in epoch 19 (so effectively 50 tokens of the user were contributing to the validator's stake at epoch 19).
- When processing the latest slash at the end of the epoch, we need to consider the first slash: the bond was contributing to the validator's stake at 19 (this is the only condition now), but not in its entirety, only 50% of it. `total_unbonded` should account for it.

This _should_ be easy to fix. Coming soon :)

**Comment by angbrav** [comment]
Closed by #38
