### ISSUE TITLE
Cubic slashing possible difference at the end of epoch and withdrawal 

### ISSUE THREAD

**Issue by tzemanovic** [informalsystems/partnership-heliax#39]
Opening an issue to discuss the thread from https://github.com/informalsystems/partnership-heliax/pull/38#issuecomment-1439901116

At the end of an epoch we collect slashes from previous and next epochs to calculate the final slash rate. This slash rate is applied to the offending validator’s stake.

When some bond to such validator is being unbonded and withdrawn, we only consider slashes that are within the start and end epochs range of the bond, which means that if e.g. there is a slash right before the start or right after the end epoch, it wouldn’t affect the slash rate that’s being applied to this bond, so it might be slashed for less than what has been applied to the total stake.

**Comment by angbrav** [comment]
As far as I understand, final slash rates are fixed when the slash is processed at the end of an epoch. Then when slashing at unbonding or withdrawal, we do not compute the rate again but use the one computed when the slash was processed at the end of the epoch. This is why I think we are slashing the same exact amount.

If my understanding isn't correct, could you provide a simple example referring to the pseudocode that highlights the problem?

**Comment by brentstone** [comment]
I think I had some small holes in my understanding when I initially commented on about this on #38, but I do agree after @angbrav's clarification that what he is saying is best and should take care of our concern more easily than we were previously thinking.

**Comment by tzemanovic** [comment]
Thanks for checking this! I agree that in the model this is handled properly with storing the final slash rate to be applied when withdrawing, so I'll close this issue
