### ISSUE TITLE
Fix validator over-slashing from multiple infractions in the same epoch

### ISSUE THREAD

**Issue by brentstone** [informalsystems/partnership-heliax#46]
If a validator commits more than one infraction in the same epoch, the current pseudocode can over-slash and sometimes even cause the validator stake to go negative. We should handle multiple slashes from one validator by adding their rates for an effective slash rate that is capped at 100%.

**Comment by angbrav** [comment]
Could we come up with a property/invariant that should be guaranteed when multiple infractions occur within a small epoch window?

**Comment by angbrav** [comment]
Total amount of tokens should be constant since we are not minting or burning tokens: slash_pool + pos_account + sum{balances}.
