### ISSUE TITLE
Delay processing slashes to include all correlated

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#47]
[from Slack conversation]
@brentstone:
I wonder if an infraction committed in epoch `n` should be processed at the end of epoch `n + unbonding_len + cubic_slash_window_width` rather than `n + unbonding_len` to always ensure that we compute the rate for the infraction in `n` considering all associated slashes.

If an infraction committed in `n` is discovered in the middle of `n + unbonding_len` but also a different infraction in `n+1` is discovered in the middle of `n + 1 + unbonding_len`, then the slash rate of `n` is going to be computed at the end of `n + unbonding_len` without considering the slash from `n + 1`, even though cubic slashing would consider these correlated.

**Comment by angbrav** [comment]
@tzemanovic:
I agree we should consider the window width, but shouldn’t it also include pipeline length? i.e `n + pipeline_len + unbonding_len + cubic_slash_window_width`

**Comment by angbrav** [comment]
I agree. To guarantee that all associated slashes are considered when computing a rate, we need to process slashes at `n + unbonding_len + cubic_slash_window_width`. @tzemanovic I could not figure out why we need to add `pipeline_len`, could you elaborate a bit what your concern is?

Note that changing when slashes are processed will affect other parts of the PoS system, such as the unbonding period duration.

**Comment by brentstone** [comment]
I also don't think we need `pipeline_len` in here. The current spec and implementation processes slashes `unbonding_len` epochs after the infraction.

Thanks for the note @angbrav on other effects on the PoS system - in this case, should `unbonding_len` itself be a function of the `cubic_slash_window_width`? Or maybe we just make unbonds withdrawable at `pipeline_len + unbonding_len + cubic_slash_window_width` after the tx submission?

**Comment by angbrav** [comment]
> Or maybe we just make unbonds withdrawable at pipeline_len + unbonding_len + cubic_slash_window_width after the tx submission?

I am thinking of something like this. I'll take a closer look tomorrow and also see if it may affect other parts

**Comment by tzemanovic** [comment]
> I also don't think we need `pipeline_len` in here. The current spec and implementation processes slashes `unbonding_len` epochs after the infraction.

Oh, is that accurate? It says “This is the final epoch before the stake that was used to commit the infraction can be fully unbonded and withdrawn.” We can only withdraw starting from `pipeline_len + unbonding_len`.

**Comment by brentstone** [comment]
Completed in #54
