### ISSUE TITLE
Quint spec: change slash rate to a `Dec` type

### ISSUE THREAD

**Issue by brentstone** [informalsystems/partnership-heliax#59]
This is technically more accurate, but I know testing recently has only considered slash rates of 1.0 and may want to continue doing this. However, making this a `Dec` gives the flexibility to do more testing that is more aligned with Namada.

**Comment by angbrav** [comment]
Agree! That was my intention when I added the library. Did not have time yet to integrate it in the spec: lower priority than redelegation IMO. It is good though that you created the issue to keep track of it

**Comment by angbrav** [comment]
Not planning to do it.
