### ISSUE TITLE
Overlap bonding and unbonding

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#6]
### Potential problem with unbonding period

- Let cur_epoch be the current epoch.
- Assume an unbond transaction tx makes it to a block in cur_epoch

**Claim 1: There cannot be a bond > 0 at any epoch > cur_epoch + pipeline_length.**
- Positive bonds are only written in the pipeline_length offset, and no bond could have been written for an epoch > cur_epoch at this point in time.
- Note that there could be negative bonds up to the unbonding_length offset, but we are not gonna create any unbond out of those.

**Claim 2: For any unbond u created by executing tx, we have that u.end - u.start >= unbonding_length - pipeline_length.**
- Let b a bond from which u is created.
- The model sets u.start to the epoch at which the bond was materialized (this is the epoch at which it was created plus the pipeline_length offset).
- By Claim 1 then u.start <= cur_epoch + pipeline_length.
- On the other hand, the model sets u.end to cur_epoch+unbonding_length.
- Then u.end - u.start >= unbonding_length - pipeline_length, as required.

Assuming the model captures what the PoS module is intended to do, **this may be concerning:**

- The model allows start unbonding before a bond is materialized. Therefore, an amount that is effectively bonded at an epoch n can be unbonded in less than unbonding_length epochs.
- Things break badly if pipeline_length >= unbonding_length.

**Comment by sergio-mena** [comment]
This seems intended/resolved to us
