### ISSUE TITLE
Quint spec: make `enqueuedSlashes` be a map `Epoch -> List[Slash]`

### ISSUE THREAD

**Issue by brentstone** [informalsystems/partnership-heliax#60]
Currently, `enqueuedSlashes` in the `PosState` is a map `Epoch -> Set[Slash]`, where a `Slash` has fields `epoch`, `validator`, and `rate`. In Namada, a validator may misbehave more than once in the same epoch, and we should account for multiple infractions that result in identical `Slash` objects.

**Comment by angbrav** [comment]
Working on it in https://github.com/informalsystems/partnership-heliax/pull/63 

Edit: addressed in https://github.com/informalsystems/partnership-heliax/pull/63 by transforming the set into a bag to allow duplicates.

**Comment by angbrav** [comment]
Closed by #63
