### ISSUE TITLE
Discrepancy between Quint and Namada: when slashes are processed

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#71]
In Namada, slashes are processed at the beginning of an epoch while in the Quint spec, slashes are processed at the end of an epoch.

**Comment by angbrav** [comment]
I have a question here @brentstone @tzemanovic.

In Quint, when evidence is submitted for an infraction committed at epoch `e_1`, we schedule its processing at `e_2=e_1+unbonding+cubic`. This means we will slash the validator at the end of `e_2`. Since in Namada slashes are processed at the beginning of epochs, at the beginning of which epoch would the slash be processed `e_2` or `e_2+1`?

**Comment by brentstone** [comment]
> In Quint, when evidence is submitted for an infraction committed at epoch `e_1`, we schedule its processing at `e_2=e_1+unbonding+cubic`. This means we will slash the validator at the end of `e_2`. Since in Namada slashes are processed at the beginning of epochs, at the beginning of which epoch would the slash be processed `e_2` or `e_2+1`?

At the beginning of `e_2+1`. We tried to make everything mirror the Quint spec as close as possible

**Comment by angbrav** [comment]
Agreed to revisit later; maybe take a look to Namada's code

**Comment by angbrav** [comment]
Not planning to do it.
