### ISSUE TITLE
redelegated bonds delta not being removed on unbonding

### ISSUE THREAD

**Issue by tzemanovic** [informalsystems/partnership-heliax#75]
When unbonding, we prioritize unbonding redelegated bonds. For a delegator, the sum of redelegated bonds in the validator from which it is unbonding should be included in the bond delta amount. In other words, the bond delta amount in epochs from which we're unbonding must be >= to sum of redelegation bonds from all source validator in the same start epoch.

As an example, start with a validator with a total bond of 3 tokens:

- a regular delegation of 2 tokens starting from epoch 8
- an incoming redelegation from the same delegator for 1 token from the same epoch
- the delegator requests to unbond 1 token
- resultUnbonding will have new = {8, 2} and empty toRemove set (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L95)
- computeModifiedRedelegation gets called because the redelegatedBonds.has(resultUnbonding.new.start) (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L101)
- but it returns early because totalRedelegated (1) <= amount (1) - in the comment above this check "... all redelegated bonds must be unbonded" (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/helper-functions.qnt#L117)
- back in def unbond, we attempt to remove resultUnbonding.toRemove, but this set is empty so the redelegation does not get removed (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L103)

*edit* : corrected `resultUnbonding` new = {8, 2} instead of {8, 1} as the sum of delegation and redelegation is `3` and we're unbonding 1 token

**Comment by tzemanovic** [comment]
The first example doesn't break the invariant.

With a slight variation; Again, start with a validator with a total bond of 3 tokens, but with a larger redelegation than delegation:
- a regular delegation of 1 tokens starting from epoch 8
- an incoming redelegation from the same delegator for 2 token from the same epoch
- the delegator requests to unbond 2 token
- `resultUnbonding` will have `new = {8, 1}` and empty `toRemove` set (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L95)
- `computeModifiedRedelegation` gets called because the `redelegatedBonds.has(resultUnbonding.new.start)` (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L101)
- but it returns early because `totalRedelegated (2) <= amount (2)` - in the comment above this check "... all redelegated bonds must be unbonded" (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/helper-functions.qnt#L117)
- back in `def unbond`, we attempt to remove `resultUnbonding.toRemove`, but this set is empty so the redelegation does not get removed (https://github.com/informalsystems/partnership-heliax/blob/5f6e59f1dc9993da556fbc16a823e808bbdc6b89/2023/Q2/artifacts/PoS-quint/namada-redelegation.qnt#L103)
- now the bond is `8 -> 1` but redelegatedBonds still has `8 -> (src_validator -> 2)`

**Comment by angbrav** [comment]
Agree, this is a bug.

**Comment by angbrav** [comment]
Fixed by https://github.com/informalsystems/partnership-heliax/pull/76
