### ISSUE TITLE
Brainstorming for Namada rewards

### ISSUE THREAD

**Issue by brentstone** [informalsystems/partnership-heliax#80]
The goal here is to mint new tokens as inflationary rewards and have them apply to validators' voting power.

Here are some current resources / material that can be useful for planning the specification:
- https://specs.namada.net/economics/proof-of-stake/reward-distribution
- https://github.com/anoma/namada/blob/brent/apply-rewards-to-voting-power/proof_of_stake/applying_rewards_to_voting_power.md

Some important notes:
- We rely on a data structure called the `rewards products`, which is of the form `Epoch -> Dec`. This is described in the first link above. The idea is that the `Dec` numbers in here are multipliers of stake that encode the effective stake including rewards.
- There is a one `rewards products` for validators and one for delegators, which accounts for validator's commissions.
- We want to update the validator deltas and validator sets eagerly at pipeline epoch as soon as the new inflation amount is computed.
- The true amount of bonds is computed lazily by applying the rewards products to the bonds.

**Comment by brentstone** [comment]
@angbrav @tzemanovic @cwgoes 

Some brainstorming notes for how we will move forward with a claim-based rewards system. Please feel free to edit this.

- Want to have some lib function`fn claim_rewards(delegator, validator)` that can have an associated Namada Tx.
- Need a method of determining the amount of rewards to give based on the previous claim. Two possible options:
   - Record last claim epoch for each delegator-validator pair in storage
   - Modify the rewards products in storage such that future computations account for this
- Claiming rewards and slashing
   - Should we only allow rewards to be claimed for epochs that are outside of the slash processing epoch window? Should be taking into account slashes when computing rewards as well

- Must account for not losing information in the event multiple redelegations occur without a claim to any rewards within that time period
   - Perhaps an unbond (called by redelegation) will automatically claim rewards for the lifetime of that bond
      - Issue with this is that a bond will accumulate rewards for `pipeline len` epochs after the unbond is initiated
   - Possible approaches:
      - Prevent some number of redelegations until rewards are claimed (client error)
      - Queue up all unbond txs for the protocol to iterate through `pipeline_len` epochs later and send out the remaining rewards (seems not ideal to force the protocol to do during an epoch change)
      - Write some data in storage to keep as a record for when a claim tx is actually sent
         - Delegator, validator, raw unbond amount, epoch that unbond is initiated
         - Then later during a claim, can use this data to compute the rewards for epochs after the unbond tx was initiated but was still contributing to voting power
         - Perhaps can just automatically claim rewards for all this data in addition to the `validator` associated with the active bonds in the `claim_rewards(delegator,validator)` call

**Comment by brentstone** [comment]
@cwgoes and I chatted on Friday a bit more about rewards. There are two changes to the above that are necessary and could make things easier to implement as well.
1) Can no longer use the exact `rewards_products` since these are multiplicative numbers that account for the auto-bonding feature. Values should now be additive or just the fraction of `reward_tokens / validator_stake`.
2) When tokens are unbonded, do not give them rewards after the unbond transaction in epochs when they still contribute to voting power (`pipeline_len`). Just compute rewards up to the current epoch.

As a result from `2)`, during an unbond transaction, we can compute rewards for the lifetime of the bond from `bond_start_epoch` to `current_epoch`, and then create a similar object as a typical `unbond` in storage: inside of some `rewards` map for the `source_address` of the unbond, we would have `bond_start_epoch -> current_epoch -> reward_amount`. Known slashes could be applied. This would be done for every call of `unbond`, so while unbonding and redelegating. This should also take care of tracking rewards from old redelegations that have not been claimed yet.

We also still need to wait long enough to ensure that all slashes can be applied to the rewards before a user claims them, so we can also make the rewards claimable starting at the `withdrawable_epoch`. Furthermore, I wonder if we do not even need a `claim` tx, perhaps instead just expanding the `withdraw` tx to withdraw both normal unbonds and rewards, whose data in storage will look quite similar.

**Comment by tzemanovic** [comment]
Given that we need to wait for withdrawable epoch to consider slashes, I'd say for simplicity sake there's not much point in applying slashes at unbonding and instead we should apply them all when withdrawing, similarly to the unbonded amount. As for the rewards epoch range, we could then take rewards from `bond_start_epoch` to `current_epoch + unbonding_len` to make sure that there are no left-over rewards for this bond when it's withdrawn.

I think for redelegation, it would be too complicated to transfer rewards as we'd either have to keep some left-over unclaimed rewards from the source validator that remain slashable or "transfer slashes" to the destination validator like we do for the deltas, so imho it may be simpler to leave rewards unclaimed until the owner requests them (either via unbonding or direct claim tx).

So there could be 2 ways of claiming rewards which can be transferred instantaneously to the owner's account:
- new "claim" tx that only takes rewards that are no longer slashable
- extended "withdraw" tx that takes the rewards corresponding for the withdrawn delta(s)

And we could also add "bond rewards" tx that claims rewards that are no longer slashable and bonds them to a given validator at pipeline offset (this can be a composition of claim & bond).

**Comment by angbrav** [comment]
I am a bit confused about slashing: why do we need to slash rewards if these have never been contributing to a validator's stake?

Do you mean something else? Something like maybe we computed rewards fro epoch `e` and in a future epoch evidence is submitted indicating that the validator misbehaved at that epoch and we want to `cancel` the rewards...

**Comment by tzemanovic** [comment]
> Do you mean something else? Something like maybe we computed rewards fro epoch `e` and in a future epoch evidence is submitted indicating that the validator misbehaved at that epoch and we want to `cancel` the rewards...

I think that's it, yes. We calculate rewards from current validators' stakes, but when those then get slashed we should retrospectively reduce the rewards that were given too

**Comment by angbrav** [comment]
I think it is then simpler to just compute rewards when the slashing window is over

**Comment by cwgoes** [comment]
Let's not worry about slashing rewards for now, especially given that rewards aren't applied to voting powers, I don't think this is necessary for the incentive model to work.
